version: "3.8"

services:
  api_db:
    build:
      context: .
      dockerfile: ./SqlServer/Dockerfile
    user: root
    restart: always
    volumes:
      - api_data:/var/opt/mssql/data
    env_file: ./.env
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P${MSSQL_SA_PASSWORD}", "-Q", "select 1"]
      interval: 1s
      retries: 20
    ports:
      - "1433:1433"

volumes:
  api_data: {}
