version: "3.8"

services:
  gameswebapi:
    build:
      context: .
      dockerfile: GamesWebApi.Presentation/Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      api_db:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - "./GamesWebApi.Tests:/src/GamesWebApi.Tests"
  api_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    volumes:
      - api_data:/var/opt/mssql/data
    env_file: ./.env
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-P${MSSQL_SA_PASSWORD}", "-Q", "select 1"]
      interval: 1s
      retries: 20
    ports:
      - "1433:1433"
    networks:
      - backend

volumes:
  api_data: {}

networks:
  backend: {}

